### ISSUE TITLE
openhab2 connection

### ISSUE THREAD

**Issue by SpawnY0815** [kubawolanin/ha-openhab#18]
I still have old hardware that is only accessible via openhab2 (openhab1 binding). For this I need an openhab2 connection. This can work entirely without login. Is this possible?

**Comment by kubawolanin** [comment]
Hi @SpawnY0815,
It should be possible in theory - REST API isn't that much different in OH2 and OH3 as far as I know.

If there's no login for it on your server, simply choose basic authentication and leave username and password empty in component's config flow:

![6c7ee99fb0e20763c5ce832777da3bb353098754](https://user-images.githubusercontent.com/2270505/145686103-9717650a-7813-4956-bcfd-ca2707b49bd8.gif)

**Comment by SpawnY0815** [comment]
Hey @kubawolanin 
unfortunately it does not work like that. I had already tested that. Without authentication data I get an error.
Is it maybe possible to add a third possibility " none" beside Basic, Token?

**Comment by kubawolanin** [comment]
@SpawnY0815 could you share what logs are saying?
Sure. it should be feasible

**Comment by SpawnY0815** [comment]
Hey @kubawolanin 
![grafik](https://user-images.githubusercontent.com/7354856/145710513-d6eabd7b-a098-4f89-a04b-aef716b119e2.png)
The credentials are probably checked for being present. So I get the message "Username/Password is wrong." when I leave the fields empty.

**Comment by kubawolanin** [comment]
Please visit Configuration > Settings > Logs in Home Assistant and see if there are errors coming from openhab integration.
Clicking on the error entry should reveal a stack trace, eg:
![Screenshot_2021-12-12-12-38-58-241_io.homeassistant.companion.android.jpg](https://user-images.githubusercontent.com/2270505/145710630-fed22d06-1c76-4839-a4f5-98ad1eb3d531.jpg)

**Comment by SpawnY0815** [comment]
There is no entry to see.
I think no log entry is generated because I don't complete the setup at all due to the credentials monitoring.
